# Generated by Django 3.2 on 2022-09-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=300, unique=True)),
                ('event_type', models.CharField(max_length=600)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('event_data', models.JSONField(default=dict)),
            ],
        ),
    ]
