# Generated by Django 3.2 on 2022-09-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlog',
            name='performed_by',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
