# Generated by Django 3.2 on 2022-09-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_eventlog_performed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlog',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
